plugins {
    id("com.github.ben-manes.versions") version "0.53.0"
}

def requiredMajor(mod) {
    if (mod.group == "org.eclipse.jetty") return "9."
    if (mod.module == "HikariCP") return "4."
    return ""
}

tasks.withType(com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask).configureEach {
    rejectVersionIf {
        candidate.version.contains("-a") || 
        candidate.version.contains("-b") ||
        !candidate.version.startsWith(requiredMajor(candidate))
    }
}

project(":") {
    task clean(type: Delete) {
        delete("distr")
    }
}
