[libraries]
gson = "com.google.code.gson:gson:2.13.2"
small-json = "io.github.osobolev:small-json:1.4"

jetty = "org.eclipse.jetty:jetty-servlet:9.4.58.v20250814"
commons-fileupload = "commons-fileupload:commons-fileupload:1.6.0"
commons-io = "commons-io:commons-io:2.21.0"
jose4j = "org.bitbucket.b_c:jose4j:0.9.6"

freemarker = "org.freemarker:freemarker:2.3.34"
owasp-sanitizer = "com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:20260313.1"

hikari = "com.zaxxer:HikariCP:4.0.3"
postgres-jdbc = "org.postgresql:postgresql:42.7.10"

slf4j-nop = "org.slf4j:slf4j-nop:2.0.17"
